# Generated by Django 4.2.1 on 2023-06-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                (
                    'type',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')],
                        verbose_name='Тип звена',
                    ),
                ),
                ('debt', models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    'hierarchy',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'First'), (1, 'Second'), (2, 'Third')], verbose_name='Иерархия'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                (
                    'contact',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='sales_chain.contact',
                        verbose_name='Контакты',
                    ),
                ),
                ('product', models.ManyToManyField(to='sales_chain.product', verbose_name='Продукты')),
                (
                    'supplier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='sales_chain.chainlink',
                        verbose_name='Поставщик',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
            },
        ),
    ]
