# Generated by Django 4.2.1 on 2023-06-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='product',
            field=models.ManyToManyField(blank=True, to='sales_chain.product', verbose_name='Продукты'),
        ),
    ]
