# Generated by Django 4.2.1 on 2023-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales_chain', '0003_alter_chainlink_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainlink',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Задолженность'),
        ),
    ]
